# Generated by Django 4.2.28 on 2026-02-11 04:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF6B6B", "Red"),
                            ("#4ECDC4", "Teal"),
                            ("#45B7D1", "Blue"),
                            ("#FFA07A", "Orange"),
                            ("#98D8C8", "Mint"),
                            ("#F7DC6F", "Yellow"),
                            ("#BB8FCE", "Purple"),
                            ("#85C1E2", "Sky Blue"),
                        ],
                        default="#4ECDC4",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "position",
                    models.IntegerField(default=0, help_text="For manual ordering"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="tasks.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["position", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="tasks_user_id_a53e17_idx"
                    ),
                    models.Index(
                        fields=["user", "priority"], name="tasks_user_id_e06a45_idx"
                    ),
                    models.Index(
                        fields=["user", "due_date"], name="tasks_user_id_20dbf7_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="tasks_user_id_90ebe9_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["user", "name"], name="tags_user_id_eb4e0f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("user", "name")},
        ),
    ]
