# Generated by Django 4.2.28 on 2026-03-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_completed_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "position"], name="tasks_user_id_8d8389_idx"
            ),
        ),
    ]
